// Generated by CoffeeScript 1.6.3
/*
	Name:
	charme_schema

	Info:
	Global Context Definitions
*/


(function() {
  this.charme_schema = {
    global: {
      'offer': {
        attributes: [
          {
            id: "Title",
            type: "string",
            name: "Title:"
          }, {
            id: "price",
            type: "moneyamount",
            name: "Price:"
          }, {
            id: "Curreny:",
            type: "currency",
            name: "Currency:"
          }, {
            id: "Sell:",
            type: "productcategory",
            name: "Category:"
          }
        ]
      },
      'review': {
        attributes: [
          {
            id: "title",
            type: "string",
            name: "Title:"
          }, {
            id: "target",
            type: "entity",
            name: "Entity:"
          }, {
            id: "rating",
            type: "5stars",
            name: "Rating:"
          }
        ]
      },
      'publicevent': {
        attributes: [
          {
            id: "Title",
            type: "string",
            name: "Title:"
          }, {
            id: "location",
            type: "location",
            name: "Location:"
          }, {
            id: "startTime",
            type: "datetime",
            name: "Start Time:"
          }, {
            id: "endTime",
            type: "datetime",
            name: "End Time:"
          }, {
            id: "audience",
            type: "int",
            name: "Guests:"
          }
        ]
      },
      'move': {
        attributes: [
          {
            id: "startLocation",
            type: "area",
            name: "Start:"
          }, {
            id: "endLocation",
            type: "location",
            name: "Destination:"
          }, {
            id: "startTime",
            type: "datetime",
            name: "Start Time:"
          }, {
            id: "endTime",
            type: "datetime",
            name: "End Time:"
          }, {
            id: "seats",
            type: "int",
            name: "Seats"
          }
        ]
      }
    }
  };

  CharmeModels.ListOperations = (function() {
    function ListOperations() {}

    ListOperations.makeUniqueList = function(list) {
      var uniqueNames;
      uniqueNames = [];
      $.each(list, function(i, el) {
        if ($.inArray(el, uniqueNames) === -1) {
          return uniqueNames.push(el);
        }
      });
      return uniqueNames;
    };

    return ListOperations;

  })();

  CharmeModels.Signature = (function() {
    Signature.hash;

    Signature.revision;

    /*
    
    	Name:
    	Signature(originalMessage)
    
    	Info:
    	Generate a signature with the users private key.
    	
    	Params:
    	message:string:The message you want to sign
    
    	Location:
    	crypto.js
    
    	Code:JS:
    	var signature = crypto_sign("hallo welt", );
    */


    function Signature(originalMessage) {
      var key1, rsa;
      this.originalMessage = originalMessage;
      rsa = new RSAKey();
      key1 = getKeyByRevision(0);
      this.revision = key1.revision;
      rsa.setPrivateEx(key1.rsa.rsa.n, key1.rsa.rsa.e, key1.rsa.rsa.d, key1.rsa.rsa.p, key1.rsa.rsa.q, key1.rsa.rsa.dmp1, key1.rsa.rsa.dmq1, key1.rsa.rsa.coeff);
      this.hash = rsa.signStringWithSHA1(originalMessage);
    }

    /*
    	
    	Name:
    	Signature.Verify(hash, message2verify, publicKey)
    
    	Info:
    	Verify a signature. Returns TRUE or FALSE
    
    	Params:
    	signature:string:The signature to check
    	message:string:The message you want to check
    	publicKey:object:The publicKey (usually from key directory)
    
    	Location:
    	crypto.js
    
    	Code:JS:
    	// TODO
    */


    Signature.Verify = function(hash2Check, message2verify, publicKey) {
      var key1, result, x509;
      key1 = getKeyByRevision(0);
      alert("SIGNATURE VERIFICATION NOT WORKING YET!!!");
      x509 = new X509();
      x509.readCertNE(key1.rsa.rsa.n, key1.rsa.rsa.e);
      result = x509.subjectPublicKeyRSA.verifyString(message, signature);
      if (result === true) {
        return true;
      } else {
        return false;
      }
    };

    Signature.keyToPem = function(n, e) {
      var i, linecount, pem, pemnew, rsa;
      rsa = new RSAKey();
      rsa.setPublic(n, e);
      pem = rsa.publicKeyToX509PemString();
      linecount = Math.ceil(pem.length / 64);
      pemnew = "-----BEGIN PUBLIC KEY-----\n";
      i = 0;
      while (i < linecount) {
        pemnew += pem.substr(i * 64, 64) + "\n";
        i++;
      }
      return pemnew += "-----END PUBLIC KEY-----";
    };

    Signature.prototype.toJSON = function() {
      return {
        keyRevision: this.revision,
        hashvalue: this.hash
      };
    };

    Signature.showDialog = function() {
      return $.get("templates/box_checksign.html", function(d) {
        var template;
        _.templateSettings.variable = "rc";
        template = _.template(d, null);
        return ui_showBox(template, function() {});
      });
    };

    /*
    
    		Return Form: {object, signature {keyRevision, hashvalue}}
    */


    Signature.makeSignedJSON = function(object) {
      var jsonString, signature;
      jsonString = JSON.stringify(object);
      console.log("string is");
      console.log(jsonString);
      signature = new CharmeModels.Signature(jsonString);
      return {
        object: object,
        signature: signature.toJSON()
      };
    };

    Signature.verifySignedJSON = function(object, key) {
      var str;
      str = JSON.stringify(object);
      return CharmeModels.Signature.Verify(object.signature.hashvalue, str, key);
    };

    return Signature;

  })();

  CharmeModels.Keys = (function() {
    function Keys() {}

    Keys.buildHash = function(key) {
      return CryptoJS.SHA256(CryptoJS.SHA256(key.n) + CryptoJS.SHA256(key.e));
    };

    Keys.querySignatureDirectory = function(user) {};

    Keys.makeRsaFkKeypair = function(publicKey) {
      var fastkey, randomKey, rk, rsa, rsaEncKey;
      randomKey = randomAesKey(32);
      fastkey = getFastKey(0, 1);
      rk = aes_encrypt(fastkey.fastkey1, randomKey);
      rsa = new RSAKey();
      rsa.setPublic(publicKey.n, publicKey.e);
      rsaEncKey = rsa.encrypt(randomKey);
      return {
        rsaEncKey: rsaEncKey,
        "revision": fastkey.revision,
        "randomKey": rk,
        "randomKeyRaw": randomKey
      };
    };

    return Keys;

  })();

  this.isResponsive = function() {
    return $(".header.responsive").is(":visible");
  };

  CharmeModels.Context = (function() {
    function Context() {}

    Context.getForm = function(fieldId) {
      var html, k, v, _ref;
      html = "";
      console.log(charme_schema.global["move"]);
      _ref = charme_schema.global[fieldId].attributes;
      for (k in _ref) {
        v = _ref[k];
        html += "<div style='padding:8px 0px; font-weight:bold;'>" + v["name"] + "</div>";
        if (v["type"] === "area") {
          html += "<select><option></option></select> Radius: <select><option></option></select>";
        } else if (v["type"] === "location") {
          html += "<select><option></option></select>";
        } else if (v["type"] === "string") {
          html += "<input type='text' class='box'>";
        } else if (v["type"] === "datetime") {
          html += '<input class="box" type="date">';
        } else if (v["type"] === "int") {
          html += "<input type='text' class='box'>";
        } else if (v["type"] === "moneyamount") {
          html += "<input type='text' class='box'>";
        }
        html += "<br>";
      }
      return html;
    };

    return Context;

  })();

}).call(this);
